---
- name: PowerShell DSC
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Update a configuration item
    servicenow.itsm.configuration_item:
      instance:
        host: "{{ instance }}"
        username: "{{ username }}"
        password: "{{ password }}"
      sys_id: "fecec64ac3922650d57e5c65e4013195"
      environment: production
      other:
        fault_count: 1
        classification: Development
        short_description: "AAP Job ID {{ tower_job_id }} - Server is Compliant against ACME corp CIS requirements as per codebase https://github.com.au/rippa86/AAPWINDemos"
        os_version: "{{ windows_facts.distribution }}"
        cpu_type: "{{ windows_facts.architecture2 }}"
        ram: "{{ windows_facts.memtotal_mb }}"
        cpu_core_count: "{{ windows_facts.processor_cores }}"
        dns_domain: "{{ windows_facts.windows_domain_role }}"
        cpu_name:  "{{ windows_facts.processor[2] }}"
        cpu_count: "{{ windows_facts.processor_vcpus }}"
        os: "{{ windows_facts.os_name }}"
        disk_space: "20GB"
        cpu_speed: "{{ windows_facts.processor[2] }}"
        os_domain: "{{ windows_facts.interfaces[0].dns_domain }}"
        os_service_pack: "{{ windows_facts.distribution_major_version }}"
